name: hosted_inference_api
description: "Test and evaluate, for free, over 150,000 publicly accessible machine learning models, or your own private models, via simple HTTP requests, with fast inference hosted on Hugging Face shared infrastructure."
version: 0.1.0
homepage: https://github.com/adil192/hosted_inference_api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.1
  flutter_lints: ^3.0.0
