name: huggingface_dart
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.2.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.1
  flutter_lints: ^3.0.0
